POST http://localhost:5000/api/user/signup
content-type: application/json

{
   "type": "SELLER",
   "name": "karl",
   "email": "miguelnietoo.08@gmail.com",
   "password": "123",
   "telephone": "3118526979",
   "location": "colombia",
   "urlImg": "url de la imagen",
   "storeName": "papajones",
   "storeDescription": "esta es una descripcion",
   "accountNumber": "123456978"
}