POST http://agrobackend-production.up.railway.app/api/seller/create/product/644f2d8f42a73b82fe8b6351
content-type: application/json

{
    "name": "Producto 2",
    "category": "Verdura",
    "unitSale":"kilo",
    "price":5000,
    "urlImg": "url",
    "description": "es una descripcion"
}